##########################
# LOSS FUNCTION
##########################
lossfn:
  _target_: ace_dliris.losses.CrossEntropyLoss
  to_onehot_y: true
  ce_params:
    reduction: 'mean'


##########################
# OPTIMIZER
##########################
learning_rate: 0.001

optimizer:
  _target_: torch.optim.Adam
  params: $@network.parameters()
  lr: '@learning_rate'


























